#!/usr/bin/env python3
"""DSOnline setup and management CLI.

Usage:
  python3 setup.py configure     Interactive wizard — writes .env, nginx config, docker-compose.yml
  python3 setup.py start         Build and start (or restart) Docker services
  python3 setup.py nginx         Apply nginx config and reload
  python3 setup.py deploy        Full deploy: configure → start → nginx
  python3 setup.py deconfigure   Stop container and remove all generated config files
  python3 setup.py               Interactive numbered menu
"""

import argparse
import secrets
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
ENV_FILE = SCRIPT_DIR / ".env"
NGINX_DIR = SCRIPT_DIR / "nginx"
NGINX_GENERATED = NGINX_DIR / "melonds-generated.conf"
COMPOSE_FILE = SCRIPT_DIR / "docker-compose.yml"

MAX_PLAYERS = 8

ARCHITECTURES = [
    ("auto",         "Auto-detect — Docker picks based on build host (recommended)"),
    ("linux/arm64",  "ARM64 / aarch64  — Oracle Cloud Ampere A1, Apple Silicon"),
    ("linux/amd64",  "x86_64 / amd64   — most cloud VMs, Intel/AMD"),
]

RESOLUTIONS = [
    ("1280x720",  "720p  — recommended, good balance of quality and bandwidth"),
    ("1920x1080", "1080p — full HD, higher bandwidth required"),
    ("1024x768",  "768p  — lower bandwidth"),
    ("800x600",   "600p  — minimal, for slow connections"),
]


# ── Helpers ───────────────────────────────────────────────────────────────────

def gen_password() -> str:
    return secrets.token_urlsafe(6)


def _input(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    try:
        value = input(f"{prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return value if value else (default or "")


def _run(cmd: list[str], check: bool = True, cwd: Path | None = None) -> int:
    result = subprocess.run(cmd, cwd=cwd or SCRIPT_DIR)
    if check and result.returncode != 0:
        print(f"\nCommand failed: {' '.join(cmd)}")
        sys.exit(result.returncode)
    return result.returncode


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


# ── Config generation ─────────────────────────────────────────────────────────

def _hash_password(password: str) -> str:
    try:
        result = subprocess.run(
            ["openssl", "passwd", "-apr1", password],
            capture_output=True, text=True, check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        import base64, hashlib
        digest = hashlib.sha1(password.encode()).digest()
        return "{SHA}" + base64.b64encode(digest).decode()


def generate_htpasswd(players: int, passwords: list[str]) -> None:
    for i, pw in enumerate(passwords, 1):
        hashed = _hash_password(pw)
        path = NGINX_DIR / f"player{i}.htpasswd"
        path.write_text(f"player{i}:{hashed}\n")


def write_env(players: int, domain: str, passwords: list[str], geometry: str, platform: str) -> None:
    lines = [
        "# DSOnline configuration — generated by setup.py",
        f"NUM_PLAYERS={players}",
    ]
    for i, pw in enumerate(passwords, 1):
        lines.append(f"PLAYER{i}_VNC_PASSWORD={pw}")
    lines += [
        f"VNC_GEOMETRY={geometry}",
        f"DOMAIN={domain}",
        f"PLATFORM={platform}",
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n")


def generate_nginx_conf(domain: str, players: int) -> None:
    blocks = []
    for i in range(1, players + 1):
        novnc_port = 6080 + i
        blocks.append(f"""\
    # ── Player {i} ─────────────────────────────────────────────────────────────
    location /player{i}/ {{
        auth_basic "Player {i}";
        auth_basic_user_file /etc/nginx/player{i}.htpasswd;
        proxy_pass http://127.0.0.1:{novnc_port}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }}""")

    conf = "server {\n"
    conf += "    listen 80;\n"
    conf += f"    server_name {domain};\n\n"
    conf += "\n\n".join(blocks)
    conf += "\n}\n"

    NGINX_DIR.mkdir(exist_ok=True)
    NGINX_GENERATED.write_text(conf)


def generate_docker_compose(players: int, platform: str = "auto") -> None:
    indent = "      "

    platform_line = f"    platform: {platform}\n" if platform != "auto" else ""

    fuse_block = """\
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
"""

    env_vars = "\n".join(
        f"{indent}PLAYER{i}_VNC_PASSWORD: ${{PLAYER{i}_VNC_PASSWORD:-player{i}}}"
        for i in range(1, players + 1)
    )

    ports = "\n".join(
        f'{indent}- "127.0.0.1:{6080 + i}:{6080 + i}"'
        for i in range(1, players + 1)
    )

    volume_mounts = "\n".join(
        f"{indent}- player{i}-data:/home/vncuser/.config/melonDS/player{i}"
        for i in range(1, players + 1)
    )

    volume_defs = "\n".join(
        f"  player{i}-data:\n    driver: local"
        for i in range(1, players + 1)
    )

    compose = f"""\
services:
  melonds:
    build: .
{platform_line}    container_name: melonds-multiplayer
    restart: unless-stopped
    shm_size: 512mb
{fuse_block}    environment:
      NUM_PLAYERS: ${{NUM_PLAYERS:-{players}}}
{env_vars}
      VNC_GEOMETRY: ${{VNC_GEOMETRY:-1280x720}}

    ports:
{ports}

    volumes:
{volume_mounts}
      - ./roms:/home/vncuser/roms:ro

volumes:
{volume_defs}
"""
    COMPOSE_FILE.write_text(compose)


# ── Subcommands ───────────────────────────────────────────────────────────────

def cmd_configure(_args: argparse.Namespace) -> None:
    print("\n=== DSOnline Configuration ===\n")

    # Number of players
    while True:
        raw = _input(f"How many players? (1–{MAX_PLAYERS})", default="2")
        try:
            players = int(raw)
            if 1 <= players <= MAX_PLAYERS:
                break
        except ValueError:
            pass
        print(f"  Please enter a number between 1 and {MAX_PLAYERS}.")

    # Domain
    domain = _input("Domain name or IP (e.g. play.example.com or 1.2.3.4)", default="localhost")

    # Per-player passwords
    passwords: list[str] = []
    for i in range(1, players + 1):
        raw = _input(f"VNC password for Player {i} (blank to auto-generate)", default="")
        passwords.append(raw if raw else gen_password())

    # Resolution
    print("\nResolution:")
    for i, (res, label) in enumerate(RESOLUTIONS, 1):
        marker = "  ← recommended" if i == 1 else ""
        print(f"  {i}) {res}  —  {label}{marker}")
    while True:
        raw = _input("Choose resolution", default="1")
        try:
            idx = int(raw)
            if 1 <= idx <= len(RESOLUTIONS):
                geometry = RESOLUTIONS[idx - 1][0]
                break
        except ValueError:
            pass
        print(f"  Enter a number between 1 and {len(RESOLUTIONS)}.")

    # Architecture
    print("\nArchitecture:")
    for i, (_, label) in enumerate(ARCHITECTURES, 1):
        marker = "  ← recommended" if i == 1 else ""
        print(f"  {i}) {label}{marker}")
    while True:
        raw = _input("Choose architecture", default="1")
        try:
            idx = int(raw)
            if 1 <= idx <= len(ARCHITECTURES):
                platform = ARCHITECTURES[idx - 1][0]
                break
        except ValueError:
            pass
        print(f"  Enter a number between 1 and {len(ARCHITECTURES)}.")

    # Write all output files
    write_env(players, domain, passwords, geometry, platform)
    generate_nginx_conf(domain, players)
    generate_htpasswd(players, passwords)
    generate_docker_compose(players, platform)

    print("\n=== Configuration saved ===\n")
    print(f"  .env                → {ENV_FILE}")
    print(f"  nginx config        → {NGINX_GENERATED}")
    print(f"  htpasswd files      → {NGINX_DIR}/player1.htpasswd ...")
    print(f"  docker-compose.yml  → {COMPOSE_FILE}")
    print()
    print(f"  Players:      {players}")
    print(f"  Resolution:   {geometry}")
    print(f"  Architecture: {platform}")
    print(f"  Domain:       {domain}")
    for i, pw in enumerate(passwords, 1):
        print(f"  Player {i} password: {pw}")
    print()
    print("Next steps:")
    print("  python3 setup.py start   — build and launch the container")
    print("  python3 setup.py nginx   — apply the nginx config")
    print("  python3 setup.py deploy  — do both in one step")
    print()


def cmd_start(_args: argparse.Namespace) -> None:
    if not ENV_FILE.exists():
        print(f"No .env found at {ENV_FILE}")
        print("Run 'python3 setup.py configure' first.")
        sys.exit(1)

    env = load_env()
    players = int(env.get("NUM_PLAYERS", 2))
    domain = env.get("DOMAIN", "localhost")

    print("\n=== Starting DSOnline ===\n")

    subprocess.run(
        ["docker", "compose", "down"],
        cwd=SCRIPT_DIR,
        capture_output=True,
    )

    _run(["docker", "compose", "up", "-d", "--build"])

    print(f"\n=== DSOnline is running ({players} player{'s' if players != 1 else ''}) ===\n")
    for i in range(1, players + 1):
        print(f"  Player {i}: http://{domain}/player{i}/vnc.html")
    print()
    print("Direct noVNC (no nginx):")
    for i in range(1, players + 1):
        print(f"  Player {i}: http://{domain}:{6080 + i}/vnc.html")
    print()


def cmd_nginx(_args: argparse.Namespace) -> None:
    env = load_env()
    if not env:
        print("No .env found. Run 'python3 setup.py configure' first.")
        sys.exit(1)

    domain = env.get("DOMAIN", "localhost")
    players = int(env.get("NUM_PLAYERS", 2))

    # Always regenerate from .env so the config stays in sync with setup.py.
    generate_nginx_conf(domain, players)

    print("\n=== Applying nginx configuration ===\n")

    steps = [
        (
            ["sudo", "cp", str(NGINX_GENERATED), "/etc/nginx/sites-available/melonds"],
            "Copying config to /etc/nginx/sites-available/melonds",
        ),
        (
            ["sudo", "ln", "-sf",
             "/etc/nginx/sites-available/melonds",
             "/etc/nginx/sites-enabled/melonds"],
            "Symlinking to sites-enabled",
        ),
    ]

    for i in range(1, players + 1):
        htpasswd = NGINX_DIR / f"player{i}.htpasswd"
        if htpasswd.exists():
            steps.append((
                ["sudo", "cp", str(htpasswd), f"/etc/nginx/player{i}.htpasswd"],
                f"Copying htpasswd for player {i}",
            ))
        else:
            print(f"  Warning: {htpasswd} not found — run 'configure' first.")

    steps += [
        (["sudo", "nginx", "-t"],                  "Testing nginx config"),
        (["sudo", "systemctl", "reload", "nginx"], "Reloading nginx"),
    ]

    for cmd, description in steps:
        print(f"  {description}...")
        rc = _run(cmd, check=False)
        if rc != 0:
            print(f"\nFailed at step: {description}")
            sys.exit(rc)
        print("  Done.")

    print(f"\n=== nginx configured ({players} player{'s' if players != 1 else ''}) ===\n")
    for i in range(1, players + 1):
        print(f"  Player {i}: http://{domain}/player{i}/vnc.html")
    print()


def cmd_deploy(args: argparse.Namespace) -> None:
    cmd_configure(args)
    cmd_start(args)
    cmd_nginx(args)


def cmd_deconfigure(_args: argparse.Namespace) -> None:
    print("\n=== Deconfigure DSOnline ===\n")
    print("This will:")
    print("  • Stop and remove the container")
    print("  • Delete .env")
    print("  • Delete nginx/melonds-generated.conf")
    print("  • Reset docker-compose.yml to the 2-player default")
    print()

    raw = _input("Continue? [y/N]", default="N")
    if raw.lower() not in ("y", "yes"):
        print("Aborted.")
        return

    # Stop container
    print("\n  Stopping container...")
    subprocess.run(["docker", "compose", "down"], cwd=SCRIPT_DIR, capture_output=True)
    print("  Done.")

    # Optionally wipe volumes (save data)
    raw = _input("  Delete save data volumes? This permanently erases all player saves [y/N]", default="N")
    if raw.lower() in ("y", "yes"):
        print("  Removing volumes...")
        subprocess.run(["docker", "compose", "down", "-v"], cwd=SCRIPT_DIR, capture_output=True)
        print("  Volumes removed.")

    # Remove generated files
    for i in range(1, MAX_PLAYERS + 1):
        htpasswd = NGINX_DIR / f"player{i}.htpasswd"
        if htpasswd.exists():
            htpasswd.unlink()
            print(f"  Removed nginx/player{i}.htpasswd")

    for path, label in [
        (ENV_FILE,        ".env"),
        (NGINX_GENERATED, "nginx/melonds-generated.conf"),
    ]:
        if path.exists():
            path.unlink()
            print(f"  Removed {label}")

    # Reset docker-compose.yml to clean 2-player default (no pinned platform)
    generate_docker_compose(players=2, platform="auto")
    print("  Reset docker-compose.yml to 2-player default")

    print("\n=== Deconfigured ===\n")
    print("Run 'python3 setup.py configure' to set up again.")
    print()


# ── Interactive menu ──────────────────────────────────────────────────────────

MENU_ITEMS = [
    ("Configure",   "Set players, arch, domain, passwords, resolution → writes .env", cmd_configure),
    ("Start",       "Build and start (or restart) Docker services",                   cmd_start),
    ("Nginx",       "Apply nginx config and reload",                                  cmd_nginx),
    ("Deploy",      "Full deploy: configure + start + nginx",                         cmd_deploy),
    ("Deconfigure", "Stop container and remove all generated config files",           cmd_deconfigure),
]


def show_menu(args: argparse.Namespace) -> None:
    while True:
        print("\n=== DSOnline Setup ===\n")
        for i, (name, desc, _) in enumerate(MENU_ITEMS, 1):
            print(f"  {i}) {name:<12} {desc}")
        print(f"  {len(MENU_ITEMS) + 1}) Exit")
        print()

        raw = _input("Choose", default="")
        try:
            choice = int(raw)
        except ValueError:
            print("  Invalid choice.")
            continue

        if choice == len(MENU_ITEMS) + 1:
            break
        if 1 <= choice <= len(MENU_ITEMS):
            MENU_ITEMS[choice - 1][2](args)
        else:
            print("  Invalid choice.")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="setup.py",
        description="DSOnline setup and management CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "commands:\n"
            "  configure    Interactive wizard — writes .env, nginx config, docker-compose.yml\n"
            "  start        Build and start Docker services\n"
            "  nginx        Apply nginx config and reload\n"
            "  deploy       Full deploy: configure + start + nginx\n"
            "  deconfigure  Stop container and remove all generated config files\n"
            "  (no args)    Interactive numbered menu"
        ),
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=["configure", "start", "nginx", "deploy", "deconfigure"],
        help="Subcommand to run (omit for interactive menu)",
    )
    args = parser.parse_args()

    dispatch = {
        "configure":   cmd_configure,
        "start":       cmd_start,
        "nginx":       cmd_nginx,
        "deploy":      cmd_deploy,
        "deconfigure": cmd_deconfigure,
    }

    if args.command:
        dispatch[args.command](args)
    else:
        show_menu(args)


if __name__ == "__main__":
    main()
